spring.application.name=Micro-Project-Auth-Server
spring.jpa.hibernate.ddl-auto=update
server.port=${SERVER_PORT:9000}
server.forward-headers-strategy=framework
app.auth-server-url=${AUTH_SERVER_URL:http://localhost:8080}
